package org.cwi.waebric.scanner.token;

public enum HTMLKeyword {
	
	// HTML
	HTML, HEAD, BODY, 
	
	// HEAD
	TITLE, ISINDEX, LINK, META,
	
	// BODY
	ADDRESS, H, P, HR, CENTER, MATH, DIV, A, IMG, 
	B, I, U, S, BIG, SUB, SUP, TT, SMALL, STRONG, 
	CODE, CITE, EM, ABBREV, SAMP, VAR, DFN, AUTHOR, 
	PERSON, KBD, Q, ACRONYM, DELETE, INS, TABLE, 
	UL, OL, DL, MENU, FORM, DIR, 
	
	BGCOLOR, TEXT, VLINK, BACKGROUND, 
	
	// TABLE
	CAPTION, TR, 
	
	CELLPADDING, ALIGN, BORDER, CELLSPACING, WIDTH;
	
}
